### ISSUE TITLE
FRScan throw 403 errors

### ISSUE THREAD

**Issue by navalex** [Moomooo95/moomooo95-extensions#3]
Since the last update of the website, FRScan seems to protect its images from be loaded externaly (like from paperback) with probably a cookie.
There is maybe a way to bypass the protection by getting the cookie from the chapter request ? Not sure of which cookie is responsible of this protection and how to put in into the image request.

**Comment by Moomooo95** [comment]
I checked on my side and from what I saw there is no problem with the request for the images of the chapters (no cookie needed). Some images are not loading because of the 403 error even on the site. So there must be a problem on the site side.

For example, you can see, on the site, with "Hajime No Ippo" the images of the last chapters load but do not load for the first chapters.
